# Site settings
title: dannyrb.com
email: csengineer13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A tech blog covering C#.NET, Javascript, User Experience (UX), Design, and Accessibility. 
  Authored by full-stack web developer Danny Brown as a means to promote tech literacy and 
  a better web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dannyrb.com" # the base hostname & protocol for your site
twitter_username: danny_brown13
github_username:  csengineer13

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
permalink: '/posts/:title/'
exclude: [node_modules, package.json, yarn.lock, gulpfile.js, Gemfile, Gemfile.lock, readme.md]